#!/bin/bash

set -e

WORK_DIR="userbot"
mkdir -p $WORK_DIR

disp () {
    echo "-----> $*"
}

indent () {
    sed -u 's/^/       /'
}

_done () {
    echo -e "Feito\n" | indent
}

_displaylogo () {
    echo '
=== KannaX ===                              
'
}

get_branch () {
    local branch
    if [[ $PREF_BRANCH ]]
    then
        branch=$(echo $PREF_BRANCH | xargs)
    else
        branch=master
    fi
    echo "/archive/refs/heads/$branch.zip"
}

get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO =~ $regex ]]
    then 
        echo "${UPSTREAM_REPO}$(get_branch)"
    else
        echo "$(echo "aHR0cHM6Ly9naXRodWIuY29tL2NvZGUtcmdiL1VTRVJHRS1Y" | base64 -d)$(get_branch)"
    fi
}

_setup_repo () {
    local zippath
    zippath="$WORK_DIR/temp.zip"
    disp "Buscando por atualização no Repo padrão"
    wget -qq $(get_ziplink) -O "$zippath"
    _done
    disp "Descompactando os Dados"
    unzip -qq "$zippath" -d "$WORK_DIR"
    _done
    disp "Processo de Limpeza"
    rm -rf "$zippath"
    _done
}

_startbot () {
    local bot_dir
    bot_dir=$(cd $WORK_DIR && ls) && mv "$WORK_DIR/$bot_dir" "Kanna-X"
    rm -rf $WORK_DIR
    cd "Kanna-X"
    git init > /dev/null 2>&1
    echo -e "===== Iniciando KannaX =====\n" | indent
    bash run
}

begin_x () {
    _displaylogo
    sleep 5
    _setup_repo
    _startbot
}

begin_x
